version: '3'

services:
  php:
    image: php:8.0.3-alpine
    user: '1000'
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
          
    command: ["php", "-S", "0.0.0.0:8080", "-t", "./var/www/html"]
